create table user_details(aadhar_no number(12) primary key,user_name varchar(20)not null,mail_id varchar(21)not null,password varchar(13)not null,mobile_no number(10)not null);
insert into user_details values(978719581900,'Ramyadevi','Ramya@gamil.com','Ram@2000',9654348790);
SELECT *FROM user_details;

alter table userDetails1 Rename to user_details;
alter table user_details modify password varchar(300);

Delete from user_details where user_name='Vidhya';
--drop table userDetails1;

CREATE TABLE epass_apply (
    application_no            NUMBER(20)
        GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 17200000,
    applicant_name            VARCHAR(15) NOT NULL,
    aadhar_no                 NUMBER(12) NOT NULL,
    gender                    VARCHAR(10) NOT NULL,
    reason                    VARCHAR(31) NOT NULL,
    father_name               VARCHAR(19) NOT NULL,
    dob                       DATE NOT NULL,
    from_district             VARCHAR(25) NOT NULL,
    to_district               VARCHAR(21) NOT NULL,
    state                     VARCHAR(18) NOT NULL,
    travel_date               DATE NOT NULL,
    return_date               DATE NOT NULL,
    no_of_passengers          NUMBER(12) NOT NULL,
    vehicle_no                VARCHAR(15) NOT NULL,
    vehicle_no                VARCHAR(15) NOT NULL,
    mobile_no                 NUMBER(10),
    vaccination_certificate   VARCHAR(4) NOT NULL,
    CONSTRAINT user_details_epass_apply_fk FOREIGN KEY ( aadhar_no )
        REFERENCES user_details
);insert into epass_apply(applicant_name,aadhar_no,gender,reason,father_name,dob,from_district,to_district,state,travel_date,return_date,no_of_passengers,vehicle_no,mobile_no,vaccination_certificate)
            values('Navina',978719581981,'Female','Medical Emergency','Velusamy','11-03-1999','Perambalur','Trichy','Tamilnadu','15-02-2023','17-02-2023',2,8710,9801527615,'Yes');
SELECT *from epass_apply;
Select  count(*) from epass_apply;

ALTER TABLE epass_apply ADD Certificate_image blob;
alter table epassApply Rename to epass_apply;
Delete from epass_apply where application_no=17200404;
--drop table epass_apply;

create table travel_history(application_no number(15) generated by default on null as identity start with 98751001,applicant_name varchar(15)not null,gender varchar(7)not null,father_name varchar(19)not null,ticket_no varchar(13)not null,dob
date not null,aadhar_no number(12)not null,mobile_no number(10)not null,source varchar(25)not null,destination varchar(21)not null,travel_date date not null,return_date date not null,reason varchar(25)not null,no_of_passengers number(5)not null,vaccination_certificate varchar(5)not null,
   constraint user_details_travel_history_fk foreign key (aadhar_no)references user_details);
ALTER TABLE  travel_history ADD status varchar(15);

insert into travel_history(applicant_name,gender,father_name,ticket_no,dob,aadhar_no,mobile_no,source,destination,travel_date,return_date,reason,no_of_passengers,vaccination_certificate)
            values('Jayasurya','Female','Selvaraj','AD30981450','25-06-2002',765890143043,9098161540,'Dubai','Tamilnadu','19-02-2023','01-03-2023','Wedding Function',2,'Yes');
SELECT *from travel_history; 
update travel_history set status='Approved' where applicant_name='Ramyadevi';
--drop table  travel_history;
ALTER TABLE travelHistory ADD Certificate_image blob;
Delete from travel_history where application_no=98751283;

 
update epass_apply set status='Approved' where application_no=?;

commit;
select count(*) cnt from epass_apply a
union all
select count(*) emp from travel_history b ;

select (select count(*) from epass_apply) + (select count(*) from travel_history) sum from dual;

--SELECT COUNT(sum()  ) FROM epass_apply, travel_history;

select count(*) from epass_apply;
Select count(*) status from  epass_apply where status = 'Approved';
Select count(*) status from  epass_apply where status = 'Rejected';
Select count(*) status from  travel_history where status = 'Approved';
Select count(*) status from  travel_history where status = 'Rejected';

Select count(*) status from  epass_apply where status = 'Pending';
Select count(*) status from  travel_history where status = 'Pending';
commit;

Select application_no, applicant_name,aadhar_no ,gender,reason,father_name ,dob, from_district ,to_district ,state ,travel_date ,return_date,no_of_passengers ,vehicle_no, mobile_no ,vaccination_certificate,status,Certificate_image from epass_apply where status='Approved';
Select application_no, applicant_name,aadhar_no ,gender,reason,father_name ,dob, from_district ,to_district ,state ,travel_date ,return_date,no_of_passengers ,vehicle_no, mobile_no ,vaccination_certificate,status,Certificate_image from epass_apply where status='Rejected';
Select application_no, applicant_name,aadhar_no ,gender,reason,father_name ,dob, from_district ,to_district ,state ,travel_date ,return_date,no_of_passengers ,vehicle_no, mobile_no ,vaccination_certificate,status,Certificate_image from epass_apply where status='Pending';

Select application_no,applicant_name,gender,father_name,ticket_no,dob,aadhar_no,mobile_no,source,destination,travel_date,return_date,reason,no_of_passengers,vaccination_certificate,status,Certificate_image from travel_history where status='Approved';
Select application_no,applicant_name,gender,father_name,ticket_no,dob,aadhar_no,mobile_no,source,destination,travel_date,return_date,reason,no_of_passengers,vaccination_certificate,status,Certificate_image from travel_history where status='Rejected';
Select application_no,applicant_name,gender,father_name,ticket_no,dob,aadhar_no,mobile_no,source,destination,travel_date,return_date,reason,no_of_passengers,vaccination_certificate,status,Certificate_image from travel_history where status='Pending';

Select status from epass_apply where application_no=17200080;

select mail_id, password from user_details where mail_id='selvarasu@gmail.com';
Select user_name,password,aadhar_no,mobile_no from user_details where user_name='Jaya';


commit;